const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { CourseDatabase } = require("../database.cjs");
const { toTraditionalTaiwan } = require("../text-utils.cjs");
const { parseJsonResponse, normalizeNoteShape } = require("../ollama.cjs");

const root = fs.mkdtempSync(path.join(os.tmpdir(), "coursescribe-core-"));
const db = new CourseDatabase(path.join(root, "courses.sqlite"));
let reopened;
try {
  const category = db.addCategory("資料結構");
  const course = db.createCourse({ title: "本機持久化測試", categoryId: category.id, semester: "2026 春季" });
  const media = db.upsertMedia({ courseId: course.id, filePath: path.join(root, "lesson.webm"), originalName: "lesson.webm", mediaType: "video", extension: "webm", size: 10, sha256: "abc" });
  db.addSegments(course.id, null, [{ startMs: 1000, text: "简体课程内容。" }, { startMs: 1500, text: "简体课程内容。" }], "zh-TW");
  assert.equal(db.listCourses({}).length, 1);
  assert.equal(db.listSegments(course.id).length, 1, "2 秒重疊去重應合併相同片段");
  db.clearSegments(course.id);
  assert.equal(db.listSegments(course.id).length, 0, "重新轉錄前應能清除舊片段");
  db.upsertMedia({ id: media.id, courseId: course.id, filePath: path.join(root, "lesson.part"), originalName: "lesson.webm", mediaType: "video", extension: "webm", size: 10, sha256: "abc", processingStatus: "recording" });
  assert.equal(db.listProcessingMedia("recording").length, 1, "錄影中的媒體應可被啟動復原流程找到");
  reopened = new CourseDatabase(path.join(root, "courses.sqlite"));
  assert.equal(reopened.getCourseDetail(course.id).course.title, "本機持久化測試");
  const anotherCategory = reopened.addCategory("物理");
  assert.equal(reopened.setCourseCategory(course.id, anotherCategory.id).category_id, anotherCategory.id);
  assert.equal(reopened.getCourseDetail(course.id).course.category_name, "物理");
  assert.equal(reopened.listCourses({ categoryId: anotherCategory.id }).length, 1);
  assert.throws(() => reopened.setCourseCategory(course.id, "missing-category"), /分類不存在/);
  assert.equal(reopened.setCourseCategory(course.id, null).category_id, null);
  assert.equal(toTraditionalTaiwan("简体课程、软件和视频", "zh-TW"), "簡體課程、軟體和影片");
  assert.equal(toTraditionalTaiwan("简体课程", "zh-CN"), "简体课程", "簡體中文模式不應被轉換");
  reopened.trashCourse(course.id);
  assert.equal(reopened.listCourses({}).some((item) => item.id === course.id), false);
  assert.equal(reopened.listCourses({ trash: true }).some((item) => item.id === course.id), true);
  reopened.restoreCourse(course.id);
  assert.equal(reopened.listCourses({}).some((item) => item.id === course.id), true);
  assert.equal(parseJsonResponse('{"summary":"x","keyPoints":["y"]}').summary, "x");
  assert.equal(parseJsonResponse('模型前言：{"summary":"x","keyPoints":["含有 { 括號"]}').summary, "x", "JSON 前言與字串內大括號仍應可解析");
  assert.deepEqual(normalizeNoteShape({ summary: "x", keyPoints: ["y"] }), { summary: "x", sections: [{ title: "舊版重點（建議重新整理）", timestamp: "", points: [{ text: "y", quote: "", kind: "core", timestamp: "", status: "needs_review" }] }], confusions: [], reviewQuestions: [], takeaway: "", annotations: [] });
  const segment = reopened.addSegments(course.id, media.id, [{ startMs: 2000, text: "Galileo" }], "en-US")[0];
  reopened.saveTranslations(course.id, "en", [{ segmentId: segment.id, text: "Galileo" }], "gemma4:e2b");
  reopened.saveAnnotations(course.id, [{ term: "伽利略", aliases: ["gallelio"], note: "近代科學的重要人物。" }]);
  const annotated = reopened.getCourseDetail(course.id);
  assert.equal(annotated.translations.length, 1, "英文翻譯應保存於本機資料庫");
  assert.equal(annotated.annotations[0].aliases[0], "gallelio", "術語別名應保存於本機資料庫");
  const pending = reopened.createCourse({ title: "中斷轉錄測試", status: "transcribing" });
  const pendingMedia = reopened.upsertMedia({ courseId: pending.id, filePath: path.join(root, "pending.m4a"), originalName: "pending.m4a", mediaType: "audio", extension: "m4a", size: 12, processingStatus: "ready" });
  const pendingJob = reopened.createJob(pending.id, "transcription");
  reopened.updateJob(pendingJob.id, { status: "running", progress: 42, detail: "已完成第 42/110 段" });
  const pendingDetail = reopened.getCourseDetail(pending.id);
  assert.equal(pendingDetail.jobs[0].progress, 42, "單一課程詳情應包含持久化的轉錄進度");
  assert.equal(pendingDetail.jobs[0].detail, "已完成第 42/110 段", "單一課程詳情應包含目前轉錄階段");
  assert.equal(reopened.getMostRecentInterruptedTranscription().media_id, pendingMedia.id, "最近中斷的轉錄應可在下次啟動恢復");
  reopened.abandonRunningTranscriptionJobs(pending.id);
  assert.equal(reopened.getJob(pendingJob.id).status, "interrupted", "舊工作須明確標示已被恢復流程取代");
  const prior = reopened.saveNotes(course.id, { status: "ready", json: { summary: "舊筆記" }, text: "舊筆記" });
  assert.equal(prior.json.summary, "舊筆記");
  reopened.saveNotes(course.id, { status: "processing" });
  assert.equal(reopened.getNotes(course.id).json.summary, "舊筆記", "重新整理時應保留前次筆記");
  reopened.saveNotes(course.id, { status: "error", error: "模型中斷" });
  assert.equal(reopened.getNotes(course.id).json.summary, "舊筆記", "整理失敗時不得刪掉前次筆記");
  reopened.saveNoteMap(course.id, "qwen3:4b", "guide-hash", 0, "chunk-hash", { sections: [{ title: "主題", timestamp: "00:00", points: ["重點"] }], uncertainties: [] });
  assert.equal(reopened.getNoteMap(course.id, "qwen3:4b", "guide-hash", 0, "chunk-hash").sections[0].title, "主題");
  assert.equal(reopened.getNoteMap(course.id, "qwen3:4b", "different-guide", 0, "chunk-hash"), null, "不同規範不可使用舊快取");
  const main = fs.readFileSync(path.join(__dirname, "..", "main.cjs"), "utf8");
  assert.match(main, /requestSingleInstanceLock/);
  assert.match(main, /coursescribe-media/);
  assert.match(main, /TRASH_RETENTION_MS/);
  assert.match(main, /purgeExpiredTrash/);
  assert.match(main, /whisper-worker/);
  assert.match(fs.readFileSync(path.join(__dirname, "..", "ollama.cjs"), "utf8"), /segment\.startMs/);
  console.log(JSON.stringify({ ok: true, persistence: true, translations: true, annotations: true, opencc: true, ollamaJson: true, singleInstance: true }));
} finally {
  try { db.close(); } catch {}
  try { reopened?.close(); } catch {}
  fs.rmSync(root, { recursive: true, force: true });
}
